# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oZl17_oc8AIaF98ct6Mg6Sc-YdRcCWKS
"""

print("起点にしたい年月日は(初日を含まず計算されます)？")
Y_0,M_0,D_0=input(),input(),input()
print("何日前が知りたい？")
Goal_1=int(input())
def uruuy(years): #うるう年の判定
  uruuy=[]
  for year in (years):
    if year%4==0:
      uruuy.append(year)
      if year%100==0:
        del uruuy[-1]
        if year%400==0:
          uruuy.append(year)
    else:
      pass
    continue
  return uruuy
zennbuy=[]
for i in range (0,(Goal_1//365)+3):
  zennbuy.append(int(Y_0)-i)
  print(zennbuy)
print(uruuy(zennbuy))
madanam=[] #起点の年で起点の日以降を含む月
for j in range (int(M_0),13):
  madanam.append(j)
  print(madanam)
def mD(years,months): #月の日数
  D=0
  for month in (months):
    if int(month)==1 or int(month)==3 or int(month)==5 or int(month)==7 or int(month)==8 or int(month)==10 or int(month)==12:
      D+=31
    if int(month)==4 or int(month)==6 or int(month)==9 or int(month)==11:
      D+=30
    if int(month)==2:
      if int(years)in uruuy(zennbuy):
        D+=29
      else:
        D+=28
    if int(month)==0:
      D+=0
  return D
print(mD(Y_0,madanam))
rest=mD(Y_0,madanam)-int(D_0) #起点の年でまだ来ていない日数(12月30日なら1)
print(rest)
Goal=int(Goal_1)+rest
print(Goal)
def yD(years):
  D=0
  for year in (years):
    if year in uruuy(zennbuy):
      D+=366
    else:
      D+=365
      continue
  return D
umetekuy=[int(Y_0)]
while yD(umetekuy) <= Goal:
  umetekuy.append(umetekuy[-1]-1)
print(umetekuy)
Y_n=umetekuy[-1]
print(Y_n)
nokori=Goal-yD(umetekuy[:-1]) #月日部分になる日数
print("a=",nokori)
umetekum=[12]
while mD(Y_n,umetekum)<=nokori:
  umetekum.append(int(umetekum[-1])-1)
print(umetekum)
M_n=umetekum[-1]
print(M_n)
D_n=mD(Y_n,umetekum)-int(nokori)
print(D_n)
print(f"{Y_0}年{M_0}月{D_0}日の{Goal_1}日前は{Y_n}年{M_n}月{D_n}日です！")

